### ISSUE TITLE
共享key使用的是第三方api，不是openai官方的

### ISSUE THREAD

**Issue by xuzhenjun130** [Haiananan/awesomechat#1]
下单后给你的key 也是：`ac-495ff9f6-5980-416d-9121-ffa93ed83761`

更恐怖的是 他index.ts 代码这里  
```typescript
   this.API_URL = token.startsWith("ac-")
      ? `http://api.awesomechat.cn/v1/chat/completions`
      : "https://api.openai.com/v1/chat/completions";
  }
```

ac 开头的key请求的是他的代理，不是官方服务

**Comment by 906051999** [comment]
你真快,我这边连示例都没运行成功

**Comment by blain3white** [comment]
你买的是共享的，六个人共享一个账号，怎么能直接给你sk-开头的key。我的代理只是给你们六个人做个均衡，防止你一个人跑了六个人的量，你买独享就可以直接使用sk-开头的openai官方的 key 访问了。发言之前动点脑子，不想用可以别用

**Comment by xuzhenjun130** [comment]
呵呵，这么快就删除公开的 测试key了?

历史记录大家都看得见

https://github.com/Haiananan/awesomechat/commit/bd3d26b74cdf579b2d7ca3c36415549c2af5dfe2

```
## 测试key

```js
ac-495ff9f6-5980-416d-9121-ffa93ed83761
```

如果key还能用，觉得好用还想继续用的话，建议去[小铺](https://shop.haianhezi.com/?code=YT0yJmI9OQ%3D%3D)购买一个自己的key，一分钱一万。顺便记得点个Star，也让我方便统计大概多少个Star换一次测试用key。作为开发者，我希望能够有更多的人使用这个项目，这样才能够让它变得更好。如果有人滥用key，短期内我将不再提供免费测试用key。这是大家共享的测试用key，希望各位遵守原则，谢谢
````

几个人共享一个账号没问题，问题是下单后你给的key是之前就已经公布过的测试 key 

想多骗钱，动点脑子，不是所有人都会上当的

**Comment by xuzhenjun130** [comment]
这是下单截图：
![image](https://user-images.githubusercontent.com/4453516/229305097-e84a904c-cb5f-4c7a-a9da-5b64e3f35706.png)

大家可以对比一下 上面他自己公布的测试key 是不是一模一样

**Comment by blain3white** [comment]
每个企业账号日历月月初都会扣款，相当于每月重置。而且一样有什么问题，是你买来发现用不了吗？能用不就好了，四月换新的key，三月底确实是我图省事直接把卖的key当测试key用了，你介意的话我给你一个新的，这是我发货的疏忽，而不是我产品的问题。
